default:
    suites:
        cli:
            paths: [ '%paths.base%/../features/cli' ]
            contexts:
             - CliContext
        out_of_box:
            paths: [ '%paths.base%/../features/out-of-box' ]
            contexts: [ OutOfBoxContext ]
